spring.main.web-application-type: NONE

data-analysis:
  job.interval.cron: "* * * * * ?"
  file:
    path: "/home/user"
    input:
      path: "${data-analysis.file.path}/data/in"
      type: ".dat"
    output:
      path: "${data-analysis.file.path}/data/out"
      type: ".done.dat"